class DynamicGesture():
	DYNAMIC_GESTURE_UP = 100
	DYNAMIC_GESTURE_DOWN = 101
	DYNAMIC_GESTURE_LEFT = 102
	DYNAMIC_GESTURE_RTGHT = 103
	DYNAMIC_GESTURE_LEFTUP = 110
	DYNAMIC_GESTURE_RIGHTUP = 111
	DYNAMIC_GESTURE_LEFT_DOWN = 112
	DYNAMIC_GESTURE_RIGHT_DOWN = 113
	DYNAMIC_GESTURE_SCALE_UP = 121
	DYNAMIC_GESTURE_SCALE_DOWN = 122
